# Patching and updates; ensures things like security updates are enabled,
# packages are up to date, unattended-upgrades, etc.

- name: A1. Patching and Updates
  hosts: all
  become: true
  tasks:
    - name: Install python-apt for package facts
      ansible.builtin.apt:
        pkg:
          - python3-apt
        update_cache: true

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Verify unattended-upgrades and apt-listchanges are installed (if not already)
      ansible.builtin.apt:
        pkg:
          - unattended-upgrades
          - apt-listchanges
      when: "'unattended-upgrades' not in ansible_facts.packages or 'apt-listchanges' not in ansible_facts.packages"

    - name: Enable periodic apt and unattended-upgrades
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        owner: root
        group: root
        mode: "0644"
      register: out1

    - name: Run apt-get check
      ansible.builtin.apt:
        update_cache: true
      check_mode: true
      changed_when: false

    - name: Check apt-daily-upgrade.timer
      ansible.builtin.systemd_service:
        state: started
        name: apt-daily-upgrade.timer
      register: out3
      check_mode: true
      failed_when: out3.changed
